import { getPages } from "@/sanity / schemas/sanity-utils";
import "../globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Benjamins portfolio",
  description: "Generated by Next.js, Sanity.io & TS",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //get all pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
        <header className="flex items-center justify-between">
          <Link
            href={`/`}
            className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold"
          >
            Benjamin's portfolio
          </Link>
          <div className="flex items-center gap-5 text-sm text-grey-600">
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className="hover:underline">
                {page.title}
              </Link>
            ))}
          </div>
        </header>

        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
